version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    networks:
      - dokploy-network
    depends_on:
      - mongodb
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ainevis-api.rule=Host(`api.ainevis.com`)'
      - 'traefik.http.routers.ainevis-api.entrypoints=websecure'
      - 'traefik.http.routers.ainevis-api.tls.certResolver=letsencrypt'
      - 'traefik.http.services.ainevis-api.loadbalancer.server.port=3000'

  mongodb:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  mongo-data:
