export enum ENUM_RESUME_STATUS_CODE_ERROR {
  RESUME_NOT_FOUND_ERROR = 5100,
  RESUME_EXIST_ERROR = 5101,
  RESUME_IS_ACTIVE_ERROR = 5102,
  RESUME_INACTIVE_ERROR = 5103,
  RESUME_NOT_BELONG_TO_USER = 5104,
  RESUME_GENERATION_ERROR = 5215,
}
