export enum ENUM_TEMPLATE_STATUS_CODE_ERROR {
  TEMPLATE_NOT_FOUND_ERROR = 5100,
  TEMPLATE_PAYLOAD_TYPE_INVALID_ERROR = 5101,
  TEMPLATE_EXIST_ERROR = 5102,
  TEMPLATE_IS_ACTIVE_ERROR = 5103,
  TEMPLATE_INACTIVE_ERROR = 5104,
  TEMPLATE_USED_ERROR = 5105,
}
