export enum ENUM_CATEGORY_STATUS_CODE_ERROR {
  CATEGORY_NOT_FOUND_ERROR = 5100,
  CATEGORY_EXIST_ERROR = 5101,
  CATEGORY_IS_ACTIVE_ERROR = 5102,
  CATEGORY_INACTIVE_ERROR = 5103,
  CATEGORY_USED_ERROR = 5104,
}
