import { ENUM_PAGINATION_ORDER_DIRECTION_TYPE } from 'src/common/pagination/constants/pagination.enum.constant'

export const CATEGORY_REQUEST_DEFAULT_PER_PAGE = 20
export const CATEGORY_REQUEST_DEFAULT_ORDER_BY = 'createdAt'
export const CATEGORY_REQUEST_DEFAULT_AVAILABLE_SEARCH = ['user']
export const CATEGORY_REQUEST_DEFAULT_AVAILABLE_ORDER_BY = ['createdAt']
export const CATEGORY_REQUEST_DEFAULT_ORDER_DIRECTION = ENUM_PAGINATION_ORDER_DIRECTION_TYPE.ASC
