export enum ENUM_CATEGORY_REQUEST_STATUS_CODE_ERROR {
  CATEGORY_REQUEST_NOT_FOUND_ERROR = 5100,
  CATEGORY_REQUEST_EXIST_ERROR = 5101,
  CATEGORY_REQUEST_IS_ACTIVE_ERROR = 5102,
  CATEGORY_REQUEST_INACTIVE_ERROR = 5103,
  CATEGORY_REQUEST_NOT_BELONG_TO_USER = 5104,
}
